package BoundaryUI;
public class PaymentGuestScreen extends javax.swing.JFrame {

    /**
     * Creates new form PaymentScreen
     */
    public PaymentGuestScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        paymentHeader = new javax.swing.JLabel();
        paymentLine = new javax.swing.JPanel();
        cvvInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        expInput = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        cardNumberInput = new javax.swing.JTextField();
        cardNumberLabel = new javax.swing.JLabel();
        couponInput = new javax.swing.JTextField();
        couponLabel = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        cardNumberLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(java.awt.Color.black);

        backButton.setBackground(new java.awt.Color(221, 5, 37));
        backButton.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        backButton.setForeground(java.awt.Color.white);
        backButton.setText("Back");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        paymentHeader.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        paymentHeader.setForeground(java.awt.Color.white);
        paymentHeader.setText("Payment");
        paymentHeader.setToolTipText("");

        paymentLine.setMaximumSize(new java.awt.Dimension(0, 2));
        paymentLine.setMinimumSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout paymentLineLayout = new javax.swing.GroupLayout(paymentLine);
        paymentLine.setLayout(paymentLineLayout);
        paymentLineLayout.setHorizontalGroup(
            paymentLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        paymentLineLayout.setVerticalGroup(
            paymentLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        cvvInput.setBackground(new java.awt.Color(77, 77, 77));
        cvvInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cvvInput.setForeground(java.awt.Color.white);
        cvvInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cvvInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        nameLabel.setBackground(java.awt.Color.black);
        nameLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nameLabel.setForeground(java.awt.Color.white);
        nameLabel.setText("Name on Card");

        emailLabel.setBackground(java.awt.Color.black);
        emailLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        emailLabel.setForeground(java.awt.Color.white);
        emailLabel.setText("Email");

        emailInput.setBackground(new java.awt.Color(77, 77, 77));
        emailInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        emailInput.setForeground(java.awt.Color.white);
        emailInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        nameInput.setBackground(new java.awt.Color(77, 77, 77));
        nameInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nameInput.setForeground(java.awt.Color.white);
        nameInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nameInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        expInput.setBackground(new java.awt.Color(77, 77, 77));
        expInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        expInput.setForeground(java.awt.Color.white);
        expInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        expInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        cvvLabel.setBackground(java.awt.Color.black);
        cvvLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cvvLabel.setForeground(java.awt.Color.white);
        cvvLabel.setText("CVV");

        expLabel.setBackground(java.awt.Color.black);
        expLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        expLabel.setForeground(java.awt.Color.white);
        expLabel.setText("Exp");

        cardNumberInput.setBackground(new java.awt.Color(77, 77, 77));
        cardNumberInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cardNumberInput.setForeground(java.awt.Color.white);
        cardNumberInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardNumberInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        cardNumberLabel.setBackground(java.awt.Color.black);
        cardNumberLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cardNumberLabel.setForeground(java.awt.Color.white);
        cardNumberLabel.setText("Card Number");

        couponInput.setBackground(new java.awt.Color(77, 77, 77));
        couponInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        couponInput.setForeground(java.awt.Color.white);
        couponInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        couponInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        couponLabel.setBackground(java.awt.Color.black);
        couponLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        couponLabel.setForeground(java.awt.Color.white);
        couponLabel.setText("Coupon");

        payButton.setBackground(new java.awt.Color(221, 5, 37));
        payButton.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        payButton.setForeground(java.awt.Color.white);
        payButton.setText("Pay");
        payButton.setBorderPainted(false);
        payButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        backButton1.setBackground(new java.awt.Color(221, 5, 37));
        backButton1.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        backButton1.setForeground(java.awt.Color.white);
        backButton1.setText("Apply");
        backButton1.setBorderPainted(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        cardNumberLabel1.setBackground(java.awt.Color.black);
        cardNumberLabel1.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        cardNumberLabel1.setForeground(java.awt.Color.white);
        cardNumberLabel1.setText("Total: $");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(paymentLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameLabel)
                            .addComponent(cardNumberLabel)
                            .addComponent(nameInput)
                            .addComponent(cardNumberInput, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(expLabel)
                                    .addComponent(expInput, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cvvLabel)
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(cvvInput, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailLabel)
                                        .addComponent(couponLabel)
                                        .addComponent(emailInput)
                                        .addComponent(couponInput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(backButton1)))
                        .addGap(176, 176, 176))))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(paymentHeader))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(cardNumberLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paymentHeader))
                .addGap(12, 12, 12)
                .addComponent(paymentLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(cardNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cardNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cvvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cvvInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(couponLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(couponInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addComponent(backButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentGuestScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentGuestScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentGuestScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentGuestScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentGuestScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JTextField cardNumberInput;
    private javax.swing.JLabel cardNumberLabel;
    private javax.swing.JLabel cardNumberLabel1;
    private javax.swing.JTextField couponInput;
    private javax.swing.JLabel couponLabel;
    private javax.swing.JTextField cvvInput;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField expInput;
    private javax.swing.JLabel expLabel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JLabel paymentHeader;
    private javax.swing.JPanel paymentLine;
    // End of variables declaration                   
}