package BoundaryUI;

public class RegisterScreen extends javax.swing.JFrame {

    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        headerText = new javax.swing.JLabel();
        paymentLine = new javax.swing.JPanel();
        cvvInput = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        expInput = new javax.swing.JTextField();
        cvvLabel = new javax.swing.JLabel();
        expLabel = new javax.swing.JLabel();
        cardNumberInput = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        passwordInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        lastNameInput = new javax.swing.JTextField();
        firstNameInput1 = new javax.swing.JTextField();
        addressInput = new javax.swing.JTextField();
        cardNumberLabel1 = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(java.awt.Color.black);

        backButton.setBackground(new java.awt.Color(221, 5, 37));
        backButton.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        backButton.setForeground(java.awt.Color.white);
        backButton.setText("Back");
        backButton.setBorderPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton8ActionPerformed(evt);
            }
        });

        headerText.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        headerText.setForeground(java.awt.Color.white);
        headerText.setText("Join Us!");
        headerText.setToolTipText("");

        paymentLine.setMaximumSize(new java.awt.Dimension(0, 2));
        paymentLine.setMinimumSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout paymentLineLayout = new javax.swing.GroupLayout(paymentLine);
        paymentLine.setLayout(paymentLineLayout);
        paymentLineLayout.setHorizontalGroup(
            paymentLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );
        paymentLineLayout.setVerticalGroup(
            paymentLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        cvvInput.setBackground(new java.awt.Color(77, 77, 77));
        cvvInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cvvInput.setForeground(java.awt.Color.white);
        cvvInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cvvInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        nameLabel.setBackground(java.awt.Color.black);
        nameLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nameLabel.setForeground(java.awt.Color.white);
        nameLabel.setText("Name on Card");

        emailLabel.setBackground(java.awt.Color.black);
        emailLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        emailLabel.setForeground(java.awt.Color.white);
        emailLabel.setText("Email");

        emailInput.setBackground(new java.awt.Color(77, 77, 77));
        emailInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        emailInput.setForeground(java.awt.Color.white);
        emailInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emailInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        nameInput.setBackground(new java.awt.Color(77, 77, 77));
        nameInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        nameInput.setForeground(java.awt.Color.white);
        nameInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nameInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        expInput.setBackground(new java.awt.Color(77, 77, 77));
        expInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        expInput.setForeground(java.awt.Color.white);
        expInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        expInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        cvvLabel.setBackground(java.awt.Color.black);
        cvvLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cvvLabel.setForeground(java.awt.Color.white);
        cvvLabel.setText("CVV");

        expLabel.setBackground(java.awt.Color.black);
        expLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        expLabel.setForeground(java.awt.Color.white);
        expLabel.setText("Exp");

        cardNumberInput.setBackground(new java.awt.Color(77, 77, 77));
        cardNumberInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cardNumberInput.setForeground(java.awt.Color.white);
        cardNumberInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cardNumberInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        firstNameLabel.setBackground(java.awt.Color.black);
        firstNameLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        firstNameLabel.setForeground(java.awt.Color.white);
        firstNameLabel.setText("First Name");

        passwordInput.setBackground(new java.awt.Color(77, 77, 77));
        passwordInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        passwordInput.setForeground(java.awt.Color.white);
        passwordInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        passwordInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        passwordLabel.setBackground(java.awt.Color.black);
        passwordLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        passwordLabel.setForeground(java.awt.Color.white);
        passwordLabel.setText("Password");

        payButton.setBackground(new java.awt.Color(221, 5, 37));
        payButton.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        payButton.setForeground(java.awt.Color.white);
        payButton.setText("Register");
        payButton.setBorderPainted(false);
        payButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        lastNameInput.setBackground(new java.awt.Color(77, 77, 77));
        lastNameInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        lastNameInput.setForeground(java.awt.Color.white);
        lastNameInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lastNameInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        firstNameInput1.setBackground(new java.awt.Color(77, 77, 77));
        firstNameInput1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        firstNameInput1.setForeground(java.awt.Color.white);
        firstNameInput1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        firstNameInput1.setSelectionColor(new java.awt.Color(77, 77, 77));

        addressInput.setBackground(new java.awt.Color(77, 77, 77));
        addressInput.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        addressInput.setForeground(java.awt.Color.white);
        addressInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addressInput.setSelectionColor(new java.awt.Color(77, 77, 77));

        cardNumberLabel1.setBackground(java.awt.Color.black);
        cardNumberLabel1.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        cardNumberLabel1.setForeground(java.awt.Color.white);
        cardNumberLabel1.setText("Card Number");

        lastNameLabel.setBackground(java.awt.Color.black);
        lastNameLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        lastNameLabel.setForeground(java.awt.Color.white);
        lastNameLabel.setText("Last Name");

        addressLabel.setBackground(java.awt.Color.black);
        addressLabel.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        addressLabel.setForeground(java.awt.Color.white);
        addressLabel.setText("Address");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(headerText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(addressLabel)
                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(addressInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(firstNameInput1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameLabel)
                                .addComponent(nameInput)
                                .addGroup(backgroundPanelLayout.createSequentialGroup()
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(expLabel)
                                        .addComponent(expInput, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                            .addComponent(cvvLabel)
                                            .addGap(37, 37, 37))
                                        .addComponent(cvvInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(cardNumberInput))
                            .addComponent(cardNumberLabel1))
                        .addGap(45, 45, 45)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(emailLabel)
                                .addComponent(passwordLabel)
                                .addComponent(emailInput)
                                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addComponent(paymentLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerText))
                .addGap(12, 12, 12)
                .addComponent(paymentLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameInput1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addComponent(cardNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(cardNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cvvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(expLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cvvInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(expInput, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }                      

    private void backButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JTextField cardNumberInput;
    private javax.swing.JLabel cardNumberLabel1;
    private javax.swing.JTextField cvvInput;
    private javax.swing.JLabel cvvLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField expInput;
    private javax.swing.JLabel expLabel;
    private javax.swing.JTextField firstNameInput1;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel headerText;
    private javax.swing.JTextField lastNameInput;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton payButton;
    private javax.swing.JPanel paymentLine;
    // End of variables declaration                   
}